import { useState } from "react";
import axios from "axios";
import printJS from "print-js";
import baseURL from "../../../utils/baseURL";
import { Printer, Search, AlertCircle } from "lucide-react";

const Host = () => {
  const [pin, setPin] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handlePrintLookup = async (e) => {
    e.preventDefault();
    if (pin.length !== 6) return setError("Please enter a valid 6-digit PIN");

    setError("");
    setLoading(true);

    try {
      const res = await axios.get(`${baseURL}/file/${pin}`);

      if (res.data.success && res.data.fileUrl) {
        triggerBrowserPrint(res.data);
      }
    } catch (err) {
      console.error(err);
      setError(
        err.response?.data?.message || "Something went wrong fetching the file."
      );
    } finally {
      setLoading(false);
    }
  };

  const triggerBrowserPrint = async ({ fileUrl, fileType }) => {
    try {
      // 1. Fetch file data as a raw blob using axios
      const response = await axios.get(fileUrl, { responseType: "blob" });

      // 2. Extract the exact content-type directly from the server's response blob
      const fileBlob = new Blob([response.data], { type: response.data.type });
      const blobUrl = URL.createObjectURL(fileBlob);

      // 3. Robust condition checking if the asset is a PDF
      const isPdf = fileType && fileType.includes("pdf");

      // 4. Feed the local URL into print-js with the accurately detected type
      printJS({
        printable: blobUrl,
        type: isPdf ? "pdf" : "image",
        showModal: true,
        modalMessage: "Preparing document for printing...",
        onPrintDialogClose: () => {
          URL.revokeObjectURL(blobUrl);
        },
        onError: (err) => {
          console.error("PrintJS Execution Failed:", err);
          setError("Could not complete print stream.");
          URL.revokeObjectURL(blobUrl);
        },
      });
    } catch (err) {
      console.error("Printing failure:", err);
      setError("Failed to fetch and process document for printing.");
    }
  };

  return (
    <div className="w-full min-h-screen flex flex-col justify-center items-center bg-base-200 text-base-content px-4 py-8">
      <div className="card max-w-md w-full bg-base-100 border border-base-300 shadow-xl p-6 sm:p-8 flex flex-col items-center">
        
        {/* Printer Icon Container */}
        <div className="p-4 rounded-full bg-primary/10 text-primary mb-4">
          <Printer size={32} />
        </div>

        <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-center">
          Host Terminal
        </h1>
        <p className="text-base-content/60 text-xs sm:text-sm text-center mt-2 mb-6">
          Enter the 6-digit system PIN generated by the sender to access and
          deploy the document to the printer.
        </p>

        <form
          onSubmit={handlePrintLookup}
          className="w-full flex flex-col gap-4"
        >
          {/* PIN Input Container */}
          <div className="relative w-full">
            <input
              type="text"
              maxLength={6}
              placeholder="000000"
              value={pin}
              onChange={(e) => setPin(e.target.value.replace(/\D/g, ""))} // Only allow digits
              className="input input-bordered input-primary w-full tracking-[0.5em] text-center font-black text-xl sm:text-2xl h-14 pr-10 placeholder:tracking-normal placeholder:font-normal placeholder:opacity-40"
            />
            <Search
              className="absolute right-4 top-1/2 -translate-y-1/2 text-base-content/40 pointer-events-none"
              size={20}
            />
          </div>

          {/* DaisyUI Error Alert */}
          {error && (
            <div className="alert alert-error text-xs p-3 shadow-sm rounded-xl flex items-center gap-2">
              <AlertCircle size={16} className="shrink-0" />
              <span>{error}</span>
            </div>
          )}

          {/* DaisyUI Action Button */}
          <button
            type="submit"
            disabled={loading || pin.length !== 6}
            className="btn btn-primary w-full h-12 text-sm sm:text-base font-bold rounded-xl"
          >
            {loading ? (
              <>
                <span className="loading loading-spinner loading-sm"></span>
                Fetching document...
              </>
            ) : (
              "Pull & Print Document"
            )}
          </button>
        </form>
      </div>
    </div>
  );
};

export default Host;