import { useState } from "react";
import axios from "axios";
import baseURL from "../../../utils/baseURL";
import { Printer, Search, Loader2 } from "lucide-react";

const Host = () => {
  const [pin, setPin] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const handlePrintLookup = async (e) => {
    e.preventDefault();
    if (pin.length !== 6) return setError("Please enter a valid 6-digit PIN");

    setError("");
    setLoading(true);

    try {
      const res = await axios.get(`${baseURL}/file/${pin}`);

      if (res.data.success && res.data.fileUrl) {
        triggerBrowserPrint(res.data.fileUrl);
      }
    } catch (err) {
      console.error(err);
      setError(
        err.response?.data?.message || "Something went wrong fetching the file."
      );
    } finally {
      setLoading(false);
    }
  };

  // Updated Iframe Printing Engine using Local Blobs
  const triggerBrowserPrint = async (fileUrl) => {
    try {
      // 1. Fetch the file as a blob to bypass cross-origin iframe restrictions
      const response = await axios.get(fileUrl, { responseType: "blob" });

      // 2. Create a local temporary URL for the blob file
      const blobUrl = URL.createObjectURL(response.data);

      // 3. Create a hidden iframe pointing to our local blob
      const iframe = document.createElement("iframe");
      iframe.style.display = "none";
      iframe.src = blobUrl;

      document.body.appendChild(iframe);

      // 4. Wait for it to load and execute print safely
      iframe.onload = () => {
        iframe.contentWindow.focus();
        iframe.contentWindow.print();

        // 5. Clean up local memory and DOM elements
        setTimeout(() => {
          URL.revokeObjectURL(blobUrl);
          document.body.removeChild(iframe);
        }, 1000);
      };
    } catch (err) {
      console.error("Blob printing failed:", err);
      setError(
        "Failed to process document for printing. Check browser CORS settings."
      );
    }
  };

  return (
    <div className="w-full min-h-screen flex flex-col justify-center items-center bg-slate-50 px-4">
      <div className="max-w-md w-full border border-gray-200 bg-white p-8 rounded-3xl shadow-xl flex flex-col items-center">
        <div className="bg-blue-100 p-4 rounded-full text-blue-600 mb-4">
          <Printer size={32} />
        </div>

        <h1 className="text-2xl font-black text-slate-800 tracking-tight">
          Host Terminal
        </h1>
        <p className="text-gray-500 text-xs text-center mt-1 mb-8">
          Enter the 6-digit system PIN generated by the sender to access and
          deploy the document to the printer.
        </p>

        <form
          onSubmit={handlePrintLookup}
          className="w-full flex flex-col gap-4"
        >
          <div className="relative w-full">
            <input
              type="text"
              maxLength={6}
              placeholder="000000"
              value={pin}
              onChange={(e) => setPin(e.target.value.replace(/\D/g, ""))} // Only allow digits
              className="w-full tracking-[0.5em] text-center font-black text-2xl border-2 border-gray-300 rounded-2xl py-4 focus:outline-none focus:border-blue-600 transition placeholder:tracking-normal placeholder:font-normal placeholder:text-gray-300"
            />
            <Search
              className="absolute right-4 top-5 text-gray-400"
              size={20}
            />
          </div>

          {error && (
            <p className="text-red-500 text-xs font-semibold text-center">
              {error}
            </p>
          )}

          <button
            type="submit"
            disabled={loading || pin.length !== 6}
            className="w-full flex justify-center items-center gap-2 bg-blue-600 text-white py-4 rounded-2xl font-bold text-md shadow-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition"
          >
            {loading ? (
              <>
                <Loader2 className="animate-spin" size={18} /> Fetching
                document...
              </>
            ) : (
              "Pull & Print Document"
            )}
          </button>
        </form>
      </div>
    </div>
  );
};

export default Host;
